FROM golang:1.26-alpine

RUN apk add --no-cache bash git jq
RUN git clone https://github.com/bats-core/bats-core.git /tmp/bats && \
    /tmp/bats/install.sh /usr/local

WORKDIR /app
COPY . .

ENV BCQ_NO_KEYRING=1

CMD ["sh", "-c", "go test ./... && go build -o bin/bcq ./cmd/bcq && BCQ_BIN=./bin/bcq bats e2e/"]
